"""DataNeedsAgent — figures out what concrete test data the codegen needs.

Before we generate Playwright code we want to ask the user for the real
values the tests will need (mobile number, OTP source, credentials, file
paths, etc.). Otherwise the LLM bakes in placeholders like
`mobile: '1234567890'` that never actually work against the user's env.

The agent reads:
  - The Jira ticket (title + description)
  - The framework snapshot (existing .env.example, conventions)
  - The user's optional flow guidance

…and returns a small structured list of inputs that map to either:
  - .env variables the generated code will read via `process.env.X`
  - inline test-data constants the LLM should bake in directly
"""
from __future__ import annotations

import json
import logging
from typing import Any, Literal

from pydantic import BaseModel, Field, ValidationError, field_validator

from app.services.llm import LLMClient

log = logging.getLogger("qatb.data_needs")


InputType = Literal["text", "secret", "email", "url", "number", "select", "textarea"]


class DataNeedOption(BaseModel):
    value: str
    label: str = ""


class DataNeed(BaseModel):
    """One input the user must provide before codegen."""

    key: str = Field(min_length=1, max_length=80)
    label: str = Field(min_length=1, max_length=120)
    type: InputType = "text"
    placeholder: str = ""
    default: str = ""
    required: bool = True
    reason: str = ""
    options: list[DataNeedOption] = Field(default_factory=list)
    env_var: str = ""
    # When `dynamic` is true the value should be auto-generated by the test
    # code at runtime (typically via @faker-js/faker). The frontend shows
    # this as a read-only "auto-generated" row, the user provides nothing,
    # and the codegen instruction tells the LLM to call faker.x() instead.
    dynamic: bool = False
    # If dynamic=true: which faker generator to use, e.g. "internet.email",
    # "person.fullName", "phone.number", "string.uuid". Codegen uses this
    # directly: `const email = faker.internet.email();`
    faker_method: str = ""
    # Optional codegen-only hint: tells the LLM exactly how to USE this
    # value in the generated code. e.g. for OTP_SOURCE=network_response:
    # "Use page.waitForResponse(/api/otp/) and read otp from response body."
    codegen_hint: str = ""

    @field_validator("key", mode="before")
    @classmethod
    def _normalize_key(cls, v: Any) -> str:
        # Force SCREAMING_SNAKE for env-var safety
        s = str(v).strip().upper().replace("-", "_").replace(" ", "_")
        return "".join(c if c.isalnum() or c == "_" else "" for c in s)


class DataNeedsReport(BaseModel):
    inputs: list[DataNeed] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


SYSTEM = """You are a senior QA engineer. Your job is to read a Jira ticket plus optional flow guidance and decide what concrete TEST DATA the engineer needs before we generate Playwright tests.

CORE PRINCIPLE: NEVER HARDCODE EPHEMERAL VALUES. There are three categories of test data — handle each correctly:

  (A) STABLE inputs the user must provide — e.g. a known test user mobile, a fixed test password.
      → Regular field. Ask the user.

  (B) DYNAMIC inputs the test must generate at runtime — e.g. a new signup email
      that must be unique per run, a UUID for an order ID, a random full name.
      → Set `dynamic: true` and `faker_method: "internet.email"` (or similar).
        DO NOT ask the user; the codegen will call faker.x() at runtime.

  (C) DERIVED inputs the test must read from the system itself — e.g. an OTP
      that arrives via network response, a confirmation link from an email.
      → Ask the user HOW to retrieve it (a `select` field with env_var) and
        emit a `codegen_hint` telling the LLM exactly how to capture the value
        (e.g. "Use page.waitForResponse(/api/otp/) and parse `otp` from JSON body").
        NEVER ask the user for the OTP value itself.

Output ONLY this JSON shape (no prose, no markdown, no code fences):
{
  "inputs": [
    {
      "key": "TEST_USER_MOBILE",
      "label": "Mobile number for login",
      "type": "text" | "secret" | "email" | "url" | "number" | "select" | "textarea",
      "placeholder": "+91XXXXXXXXXX",
      "default": "",
      "required": true,
      "reason": "TC-001 logs in with this number",
      "options": [],                       // only for type=select
      "env_var": "TEST_USER_MOBILE",       // empty = inline value; set = process.env
      "dynamic": false,                    // true = faker-generated, user provides nothing
      "faker_method": "",                  // set when dynamic=true, e.g. "internet.email"
      "codegen_hint": ""                   // explicit instruction to the codegen LLM
    }
  ],
  "notes": ["short note for the human"]
}

RULES:
1. Keys are SCREAMING_SNAKE_CASE: TEST_USER_EMAIL, OTP_SOURCE, OTP_API_PATTERN.
2. Output 2-8 inputs. Combine related ones, don't ask the obvious.
3. SECRETS (passwords, tokens) → type "secret" + env_var set.
4. For "where does X come from?" use type "select" with 2-4 options. ALWAYS pair such a select with a `codegen_hint` per option (encode in the agent-level notes if needed) explaining how to USE the choice.
5. NEVER ask for the base URL, browser type, or Playwright config.
6. If the ticket needs no extra data, return inputs: [] and explain in notes.

PATTERNS BY FLOW TYPE:

LOGIN / OTP flows — emit something like:
  - TEST_USER_MOBILE (text, env_var) — the known test user
  - TEST_USER_PASSWORD (secret, env_var) — if password+OTP combo
  - OTP_SOURCE (select):
      • "network_response" → codegen_hint: "Use page.waitForResponse(url => /\\/otp/.test(url.url())) right after clicking Send OTP, then parse the otp field from response.json()."
      • "static_mock" → codegen_hint: "Read process.env.STATIC_TEST_OTP and fill the OTP field with it." + a follow-up input STATIC_TEST_OTP (text, env_var).
      • "sms_api" → codegen_hint: "Call the SMS provider's inbox API via APIRequestContext to fetch the latest message."
      • "no_otp" → codegen_hint: "This environment doesn't require OTP; skip the OTP step."
  Pick ONE recommended option based on the user's extra guidance.

SIGNUP / NEW-USER flows — emit these as DYNAMIC:
  - NEW_USER_EMAIL (dynamic=true, faker_method="internet.email") — codegen_hint: "Generate via faker.internet.email() inside test.beforeEach so each run is unique."
  - NEW_USER_NAME (dynamic=true, faker_method="person.fullName")
  - NEW_USER_PASSWORD (dynamic=true, faker_method="internet.password") — codegen_hint: "Generate via faker.internet.password({ length: 12 }) — strong + unique per run."

PAYMENT flows — Stripe-style:
  - TEST_CARD_NUMBER (text, default="4242424242424242") — codegen_hint: "Use Stripe's documented test card."
  - TEST_CARD_EXPIRY (text, default="12/30")
  - TEST_CARD_CVV (secret, default="123")

FILE UPLOAD:
  - SAMPLE_FILE_PATH (text) OR dynamic+faker_method="system.fileName"

SEARCH / FILTER:
  - SEED_QUERY (text) — known query that returns results

ADMIN / RBAC:
  - separate creds per role (ADMIN_EMAIL, ADMIN_PASSWORD, USER_EMAIL, USER_PASSWORD)

Be SPECIFIC. Always include `codegen_hint` for selects and for any input where the LLM might otherwise hardcode a value. Refer to the ticket's exact terms."""


def _user_prompt(ticket: dict[str, Any], flow_guidance: str, framework_snapshot: str) -> str:
    parts = [
        f"Jira ticket: {ticket.get('key', '')} — {ticket.get('title', '') or ''}",
        "",
        "Ticket description:",
        (ticket.get("description") or "(no description)")[:6000],
    ]
    if ticket.get("status"):
        parts.append(f"\nStatus: {ticket['status']}")
    if ticket.get("issuetype"):
        parts.append(f"Type: {ticket['issuetype']}")
    if flow_guidance.strip():
        parts.append("")
        parts.append("Extra guidance from the user:")
        parts.append(flow_guidance.strip()[:2000])
    if framework_snapshot.strip():
        parts.append("")
        parts.append("Framework snapshot (existing .env / conventions to align with):")
        parts.append(framework_snapshot.strip()[:6000])
    return "\n".join(parts)


async def analyze_data_needs(
    workspace_id: str,
    ticket: dict[str, Any],
    flow_guidance: str = "",
    framework_snapshot: str = "",
) -> DataNeedsReport:
    llm = await LLMClient.from_workspace(workspace_id)
    result = await llm.complete_json(
        SYSTEM,
        _user_prompt(ticket, flow_guidance, framework_snapshot),
        max_tokens=2500,
        temperature=0.0,
    )
    if not result.parsed or not isinstance(result.parsed, dict):
        log.warning("data_needs: unparseable output")
        return DataNeedsReport(notes=["Could not infer test data needs from the ticket."])
    try:
        return DataNeedsReport.model_validate(result.parsed)
    except ValidationError as e:
        log.warning("data_needs: schema mismatch: %s", e.errors()[:2])
        return DataNeedsReport(
            notes=[
                f"Data-needs analyzer output didn't match schema: {str(e.errors()[:1])[:200]}.",
            ]
        )


def format_data_values_for_codegen(values: dict[str, str], needs: list[DataNeed]) -> str:
    """Render filled-in user values + per-field codegen instructions.

    The block goes into `framework_hints`. It has three sections:

      1. .env.example values — stable inputs the user provided.
      2. Dynamic (Faker) — values the test MUST generate at runtime.
      3. Codegen instructions — per-field hints telling the LLM exactly how
         to USE the value (intercept network, call faker.x(), etc.).

    The third section is the key anti-hardcode mechanism — without it the
    codegen LLM tends to bake selected values like the OTP itself into the
    test source, which defeats the purpose.
    """
    lookup = {n.key: n for n in needs}
    env_lines: list[str] = []
    inline_lines: list[str] = []
    faker_lines: list[str] = []
    codegen_instructions: list[str] = []

    # Collect from user-provided values
    for key, value in (values or {}).items():
        if not value:
            continue
        spec = lookup.get(key)
        if spec and spec.env_var:
            env_lines.append(f"  {spec.env_var}={value}    # {spec.label}")
        elif spec:
            inline_lines.append(f"  - {spec.label} ({spec.key}): {value}")
        else:
            inline_lines.append(f"  - {key}: {value}")

        # Per-field codegen hint (works for both selects and free-text inputs).
        if spec and spec.codegen_hint:
            codegen_instructions.append(
                f"  - For {spec.key}={value!r}: {spec.codegen_hint}"
            )

    # Collect dynamic/Faker fields whether or not the user filled anything —
    # these always emit Faker code in the test.
    for n in needs:
        if not n.dynamic:
            continue
        method = n.faker_method or "lorem.word"
        faker_lines.append(
            f"  - {n.label} ({n.key}) → faker.{method}() at runtime"
        )
        if n.codegen_hint:
            codegen_instructions.append(f"  - For {n.key}: {n.codegen_hint}")
        else:
            codegen_instructions.append(
                f"  - For {n.key}: do NOT hardcode — call `faker.{method}()` "
                "inside test.beforeEach() (or directly in the test) so each run is unique."
            )

    if not env_lines and not inline_lines and not faker_lines and not codegen_instructions:
        return ""

    parts = ["", "=== Test data + codegen instructions (HARD REQUIREMENT) ==="]
    if env_lines:
        parts.append("")
        parts.append("BAKE these into the generated .env.example AND reference them via process.env in tests:")
        parts.extend(env_lines)
    if inline_lines:
        parts.append("")
        parts.append("Use these inline values in the generated tests:")
        parts.extend(inline_lines)
    if faker_lines:
        parts.append("")
        parts.append(
            "DYNAMIC values — install @faker-js/faker and import { faker } from "
            "'@faker-js/faker'. Generate fresh values inside test.beforeEach() so "
            "each run is independent:"
        )
        parts.extend(faker_lines)
    if codegen_instructions:
        parts.append("")
        parts.append(
            "HOW to use each value (read carefully — these are non-negotiable):"
        )
        parts.extend(codegen_instructions)
        parts.append("")
        parts.append(
            "Anti-patterns to AVOID:\n"
            "  ✗ Hardcoding an OTP value (e.g. `const otp = '123456';`) — capture it from the network/mock/API as instructed above.\n"
            "  ✗ Hardcoding a signup email — use faker.internet.email() so the test stays repeatable.\n"
            "  ✗ Reading process.env in test body — read it once at the top: `const MOBILE = process.env.TEST_USER_MOBILE!;`."
        )
    return "\n".join(parts)
